### PR TITLE
Update Live-here file as per the project submission

### PR DESCRIPTION
**Pull request by PrakashGatiyala**
Signed-off-by: Prakash <gatiyalap@gmail.com>

Issue No. https://github.com/deeqakkk/Journey-with-js/issues/53
I've Update Live-here file as per the project submission.

Hi @deeqakkk  Kindly review it and merge it.

### CODE REVIEW

**Review by epicdeepak — CHANGES_REQUESTED** [review]
Thank you, Prakash. Good work.
Just make a change so that "all about forms" is repeated twice. Please fix that.

**Comment by PrakashGatiyala** [comment]
> Thank you, Prakash. Good work. Just make a change so that "all about forms" is repeated twice. Please fix that.

Hi @deeqakkk  All about forms is repeated twice in repo. Which one should I remove 3rd or 12th?
image

**Comment by PrakashGatiyala** [comment]
> Thank you, Prakash. Good work. Just make a change so that "all about forms" is repeated twice. Please fix that.

Hi @deeqakkk  I've removed the 12th "All About Forms" Project link as It was copy of 3rd one in latest commit. 

please review it and merge it.

**Review by epicdeepak — APPROVED** [review]

**Comment by epicdeepak** [comment]
Thank You again, Prakash. Good work 👏🏼

**Pull request merged**
