### PR TITLE
Added Ball Fall game

### LINKED ISSUE #61: Ball Fall game using HTML, CSS and JS
Hi, I want to create a simple ball fall game with basic HTML, CSS, and JS.
In this game, the Player will have to pass a ball through hurdles and if the ball touches the boundary or it collides with any hurdle then the game will be over and the score of the player will be shown. 
Can I add my project?

### PR DESCRIPTION
**Pull request by annupriy**
Fixes #61 

# Demo Video:

https://user-images.githubusercontent.com/96621669/196147640-91dc6eca-e93f-46d2-9ca8-5a1abc67023c.mov

# Screenshot

Screenshot (173)

Screenshot (174)

:

### CODE REVIEW

**Comment by annupriy** [comment]
Hey, @deeqakkk can you tell me why the checks are not successful?

**Review by epicdeepak — CHANGES_REQUESTED** [review]
Good Work Annu, I scored 5 🥇 
Please make a separate file for javascript(script.js) and put all the js code in it.

**Comment by epicdeepak** [comment]
> Hey, @deeqakkk can you tell me why the checks are not successful?

Please ignore this, I will fix them.

**Comment by annupriy** [comment]
@deeqakkk I moved the js part into a separate file as you said.

**Review by epicdeepak — APPROVED** [review]

**Comment by epicdeepak** [comment]
> @deeqakkk I moved the js part into a separate file as you said.

Thank you @annupriy . Good Work 👏🏼

**Pull request merged**
