### PR TITLE
Microsoft homepage Added

### PR DESCRIPTION
**Pull request by saadanzarii**
Added Microsoft Homepage

### CODE REVIEW

**Review by epicdeepak — CHANGES_REQUESTED** [review]
image
Please fix this overflow. Rest of the things are good.

**Comment by saadanzarii** [comment]
Bro this project looks good in my machine...
this was my second website that i build and i wrote a pretty bad code i don't even understand. if looks good to u then merge it or otherwise i'll add my another project on it

**Comment by saadanzarii** [comment]
Screenshot from 2022-10-17 10-02-28

**Comment by epicdeepak** [comment]
> Screenshot from 2022-10-17 10-02-28

are you viewing it on 100% zoom?

**Comment by saadanzarii** [comment]
> > Screenshot from 2022-10-17 10-02-28
> 
> are you viewing it on 100% zoom?

yes i viewed in 100% zoom it looks great

**Comment by epicdeepak** [comment]
> > > Screenshot from 2022-10-17 10-02-28
> > 
> > 
> > are you viewing it on 100% zoom?
> 
> yes i viewed in 100% zoom it looks great

okay, I'm not sure what's the resolution of your monitor/laptop. But it don't looks fine on a standard monitor screen.
I'm merging this, I will fix this minor change.

**Review by epicdeepak — APPROVED** [review]

**Pull request merged**
