### PR TITLE
Google clone

### PR DESCRIPTION
**Pull request by ShrutiMishra-2002**
Google clone with dark, light, and searching functionality
dark mode:
darkmode
light mode:
lightmode

### CODE REVIEW

**Comment by ShrutiMishra-2002** [comment]
@deeqakkk please merge my pr its is totally valid

**Comment by epicdeepak** [comment]
Good work shruti🎉
Do the following changes so that I can merge it.
1. Move your files under a folder "Google-Clone" (or as per your choice)
2. remove the un-necessary commented code
3. You can use some formatting to make your code look clean.(optional)

**Comment by ShrutiMishra-2002** [comment]
@deeqakkk made all the changes

**Comment by ShrutiMishra-2002** [comment]
@deeqakkk please add the label of hacktoberfest and hacktoberfest-accepted

**Comment by epicdeepak** [comment]
> @deeqakkk please add the label of hacktoberfest and hacktoberfest-accepted

Sure, will add.

**Comment by ShrutiMishra-2002** [comment]
@deeqakkk please accept my pr!

**Review by epicdeepak — APPROVED** [review]

**Pull request merged**
