### PR TITLE
added the drum project

### PR DESCRIPTION
**Pull request by Gumanpratapsingh**
Hello Sir,
Can you check I have added the drum Project Please?

### CODE REVIEW

**Review by epicdeepak — CHANGES_REQUESTED** [review]
Please remove the un-necessary spaces in js files.

**Comment by epicdeepak** [comment]
Your project number is 9, so keep the folder name accordingly.

**Comment by Gumanpratapsingh** [comment]
Sir,Can you check now?
I removed the extra spaces and also renamed the project.

**Review by epicdeepak — APPROVED** [review]
Good work Guman, hopefully you must have learnt something while following along Angela Yu.

**Pull request merged**
