### PR TITLE
Stopwatch

### PR DESCRIPTION
**Pull request by Baba-Yaga-1**
I have added the project under #20 and I have added a live link in the Readme.md file.

Can you assign it to me and add the necessary labels?

Simple Stopwatch

### CODE REVIEW

**Review by epicdeepak — CHANGES_REQUESTED** [review]
Everything is good, just delete the readme file that is not needed.

**Comment by epicdeepak** [comment]
Your project number is 10, so keep the folder name accordingly.

**Comment by Baba-Yaga-1** [comment]
@deeqakkk I have made the changes

**Review by epicdeepak — APPROVED** [review]
Good Work baba yoga 👏🏼

**Pull request merged**
