### PR TITLE
Done The Changes Required in #18

### PR DESCRIPTION
**Pull request by saran1522**
You asked me to do some changes in PR #18 so I did them. Hope it is mergeable now. THANKS!!

### CODE REVIEW

**Comment by saran1522** [comment]
Please look at it sir

**Comment by epicdeepak** [comment]
> Please look at it sir

Saran, I asked to delete the screenshots and delete.md file. They are still there. Please delete them. Rest of the things are good.

**Comment by saran1522** [comment]
only 2 files are there 
index.html
style.css
Screenshot 2022-10-13 123209

**Comment by epicdeepak** [comment]
> only 2 files are there index.html style.css Screenshot 2022-10-13 123209

image
I was talking about this, but no worries. I will do that.

**Review by epicdeepak — APPROVED** [review]
Good Work 👏🏼 , you must have learnt about forms input.

**Comment by saran1522** [comment]
Ohh actually I was unable to see those extra files. Thanks for doing that. 🤗

**Comment by saran1522** [comment]
Yeah, I learned about forms from W3 schools and freecodecamp.

**Pull request merged**
