### PR TITLE
Added the project

### PR DESCRIPTION
**Pull request by aditya-agr**
#2 issue

### CODE REVIEW

**Comment by epicdeepak** [comment]
Make a folder and name the html file as index.html and then make a  PR.

**Comment by aditya-agr** [comment]
where I have to make folder? I had already made a folder named netflix and index.html also already exists.

**Comment by epicdeepak** [comment]
> where I have to make folder? I had already made a folder named netflix and index.html also already exists.

image
Make a folder like this with a number.

**Comment by aditya-agr** [comment]
ok now I had updated.

**Comment by epicdeepak** [comment]
> ok now I had updated.

please put all the images in a folder name asset and update the links in HTML file as well.

**Comment by aditya-agr** [comment]
Now is it OK ?

**Comment by epicdeepak** [comment]
Good work Aditya 🥳 
Keep contributing.

**Comment by aditya-agr** [comment]
Thanks 🙏

**Pull request merged**
