### PR TITLE
Builded Civo clone

### PR DESCRIPTION
**Pull request by danishhansari**
mobile first layout...

### CODE REVIEW

**Comment by epicdeepak** [comment]
> mobile first layout...

Danish, first create a issue. Than only your PR can be considered.

**Comment by danishhansari** [comment]
can u please elaborate a bit..

**Comment by epicdeepak** [comment]
> can u please elaborate a bit..

Go to the issue section, click  'new issue', add a description about your project.

**Comment by danishhansari** [comment]
I Did't

**Review by epicdeepak — APPROVED** [review]
Good work Danish, you did a great job. Hopefully you must have learnt new things while building it.

**Pull request merged**
