### PR TITLE
Basic Portfolio

### PR DESCRIPTION
**Pull request by danishhansari**
Right now i only know basic html css. And its hard to find project releted to this topic for me And i wanna take a part in hacktoberfest so thats why i make PR

### CODE REVIEW

**Comment by epicdeepak** [comment]
> Right now i only know basic html css. And its hard to find project releted to this topic for me And i wanna take a part in hacktoberfest so thats why i make PR

You can add projects like calculator, some mini games, counter etc. 

For this PR create a new folder "2-Portfolio-website"

**Comment by danishhansari** [comment]
but i don't know any of this project till now i only builded this kind of website

**Comment by epicdeepak** [comment]
Everything is good, just rename your folder to 3-Basic-portfolio and move it to the main directory.

For now your project is inside 1-background-changer.

**Comment by danishhansari** [comment]
I did all the stuff that u said

**Comment by ansari-danish** [comment]
Hey can i do my 4 PR in this repo

**Pull request merged**
