### PR TITLE
Added Spanish Translator

### PR DESCRIPTION
**Pull request by sai-karthik-p**
Added Spanish Translator App which takes English Text as input and outputs the Spanish Translation.

It contributes to #13. 

@deeqakkk Please assign #13 to me and add the proper labels.

Screenshot

### CODE REVIEW

**Review by epicdeepak — CHANGES_REQUESTED** [review]
please add a deployed link as well, so that other contributors can access it too.
For now it need an API_KEY to run properly.

**Comment by epicdeepak** [comment]
Your project number is 11, so keep the folder name accordingly.

**Review by epicdeepak — APPROVED** [review]
Good work Sai. My main aim is to help you guys get familar with using git and making contributions. Your project certainly need certain changes. But it's good for now.

**Comment by sai-karthik-p** [comment]
Thanks, @deeqakkk! :)
Do share some pointers so that I can incorporate them into future projects.

**Comment by sai-karthik-p** [comment]
Thanks, @deeqakkk! :)
Do share some pointers so that I can incorporate them into future projects.
Also, please add the "hacktoberfest-accepted" label to this PR.

**Pull request merged**
